-- =============================================================================
-- Seed de reference_aliases — generado desde los mapas *_FALLBACK de code.js.
-- Reproduce EXACTAMENTE el comportamiento hardcodeado (cert, value_translation,
-- key_equivalence, identity_discard). Las UNIDADES no van aquí (ver §4 del prompt).
-- Regenerar:  node gen_seed.js  (tras editar code.js).
-- =============================================================================

INSERT INTO reference_aliases (kind, alias, canonical) VALUES
  ('cert', 'subtel', 'CL-SUBTEL'),
  ('cert', 'chile subtel', 'CL-SUBTEL'),
  ('cert', 'cl-subtel', 'CL-SUBTEL'),
  ('cert', 'ursec', 'UY-URSEC'),
  ('cert', 'uruguay ursec', 'UY-URSEC'),
  ('cert', 'uy-ursec', 'UY-URSEC'),
  ('cert', 'enacom', 'AR-ENACOM'),
  ('cert', 'argentina enacom', 'AR-ENACOM'),
  ('cert', 'ar-enacom', 'AR-ENACOM'),
  ('cert', 'anatel', 'BR-ANATEL'),
  ('cert', 'brasil anatel', 'BR-ANATEL'),
  ('cert', 'brazil anatel', 'BR-ANATEL'),
  ('cert', 'br-anatel', 'BR-ANATEL'),
  ('cert', 'ifetel', 'MX-IFETEL'),
  ('cert', 'mexico ifetel', 'MX-IFETEL'),
  ('cert', 'méxico ifetel', 'MX-IFETEL'),
  ('cert', 'mx-ifetel', 'MX-IFETEL'),
  ('cert', 'fcc', 'GLOBAL-FCC'),
  ('cert', 'global-fcc', 'GLOBAL-FCC'),
  ('cert', 'ce', 'GLOBAL-CE'),
  ('cert', 'global-ce', 'GLOBAL-CE'),
  ('cert', 'rohs', 'GLOBAL-RoHS'),
  ('cert', 'global-rohs', 'GLOBAL-RoHS'),
  ('cert', 'reach', 'GLOBAL-REACH'),
  ('cert', 'global-reach', 'GLOBAL-REACH'),
  ('cert', 'raee', 'GLOBAL-WEEE'),
  ('cert', 'weee', 'GLOBAL-WEEE'),
  ('cert', 'global-weee', 'GLOBAL-WEEE'),
  ('cert', 'nyce', 'MX-NYCE'),
  ('cert', 'mexico nyce', 'MX-NYCE'),
  ('cert', 'méxico nyce', 'MX-NYCE'),
  ('cert', 'mx-nyce', 'MX-NYCE'),
  ('cert', 'ic', 'CA-IC'),
  ('cert', 'ca-ic', 'CA-IC'),
  ('cert', 'ptcrb', 'GLOBAL-PTCRB'),
  ('cert', 'rcm', 'AU-RCM'),
  ('cert', 'au-rcm', 'AU-RCM'),
  ('cert', 'gcf', 'GLOBAL-GCF'),
  ('cert', 'imda', 'SG-IMDA'),
  ('cert', 'eac', 'EAEU-EAC'),
  ('cert', 'telec', 'JP-TELEC'),
  ('cert', 'r&tte', 'EU-RTTE'),
  ('cert', 'ift', 'MX-IFETEL'),
  ('cert', 'rohs2', 'GLOBAL-RoHS'),
  ('cert', 'rohs 2.0', 'GLOBAL-RoHS'),
  ('cert', 'rohs2.0', 'GLOBAL-RoHS'),
  ('cert', 'e-mark', 'ECE-EMARK'),
  ('cert', 'emark', 'ECE-EMARK'),
  ('cert', 'e mark', 'ECE-EMARK'),
  ('cert', 'global-rcm', 'AU-RCM'),
  ('value_translation', 'idioma', 'language'),
  ('value_translation', 'ruta dinámica', 'dynamic routing'),
  ('value_translation', 'ruta dinamica', 'dynamic routing'),
  ('value_translation', 'protección de datos', 'data protection'),
  ('value_translation', 'proteccion de datos', 'data protection'),
  ('value_translation', 'portal cautivo', 'captive portal'),
  ('value_translation', 'plastico', 'plastic'),
  ('value_translation', 'plástico', 'plastic'),
  ('value_translation', 'metal', 'metal'),
  ('value_translation', 'acero', 'steel'),
  ('value_translation', 'aluminio', 'aluminum'),
  ('value_translation', 'sin condensación', 'non-condensing'),
  ('value_translation', 'sin condensacion', 'non-condensing'),
  ('value_translation', 'horas/minutos', 'hours/minutes'),
  ('value_translation', 'rojo', 'red'),
  ('value_translation', 'verde', 'green'),
  ('value_translation', 'azul', 'blue'),
  ('value_translation', 'negro', 'black'),
  ('value_translation', 'blanco', 'white'),
  ('value_translation', 'temporizador', 'timer'),
  ('value_translation', 'contacto seco', 'dry contact'),
  ('value_translation', 'contacto húmedo', 'wet contact'),
  ('value_translation', 'contacto humedo', 'wet contact'),
  ('value_translation', 'litio', 'lithium'),
  ('value_translation', 'lineal', 'linear'),
  ('key_equivalence', 'temp', 'temperature'),
  ('key_equivalence', 'temperatura', 'temperature'),
  ('key_equivalence', 'frecuencia', 'frequency'),
  ('key_equivalence', 'peso', 'weight'),
  ('key_equivalence', 'largo', 'length'),
  ('key_equivalence', 'ancho', 'width'),
  ('key_equivalence', 'alto', 'height'),
  ('key_equivalence', 'ganancia', 'gain'),
  ('key_equivalence', 'potencia', 'power'),
  ('key_equivalence', 'voltaje', 'voltage'),
  ('key_equivalence', 'corriente', 'current'),
  ('key_equivalence', 'conector', 'connector'),
  ('key_equivalence', 'bandas', 'bands'),
  ('key_equivalence', 'polarizacion', 'polarization'),
  ('key_equivalence', 'mount_type', 'mounting'),
  ('key_equivalence', 'mounting_type', 'mounting'),
  ('key_equivalence', 'mounting_options', 'mounting'),
  ('key_equivalence', 'montaje', 'mounting'),
  ('key_equivalence', 'relative_humidity', 'humidity'),
  ('key_equivalence', 'size', 'dimensions'),
  ('key_equivalence', 'led_indicators', 'leds'),
  ('key_equivalence', 'leds_indicator', 'leds'),
  ('key_equivalence', 'led_status', 'leds'),
  ('key_equivalence', 'status_leds', 'leds'),
  ('key_equivalence', 'ip_rating', 'ingress_protection'),
  ('key_equivalence', 'ip_code', 'ingress_protection'),
  ('key_equivalence', 'enclosure_rating', 'ingress_protection'),
  ('key_equivalence', 'waterproof', 'weather_resistant'),
  ('key_equivalence', 'weatherproof', 'weather_resistant'),
  ('key_equivalence', 'water_resistant', 'weather_resistant'),
  ('key_equivalence', 'casing_material', 'enclosure_material'),
  ('key_equivalence', 'installation', 'mounting'),
  ('key_equivalence', 'lan_ethernet_usb', 'network_features'),
  ('key_equivalence', 'serial_connectors', 'serial_port_connectors'),
  ('key_equivalence', 'reset_buttons_count', 'reset_button_count'),
  ('key_equivalence', 'has_autonegotiation', 'has_auto_negotiation'),
  ('key_equivalence', 'sim_voltage_supported_v', 'sim_supported_voltage_v'),
  ('key_equivalence', 'rs232_signals', 'serial_rs232_signals'),
  ('key_equivalence', 'rs485_signals', 'serial_rs485_signals'),
  ('key_equivalence', 'serial_baud_min_mbps', 'serial_baud_rate_min_mbps'),
  ('key_equivalence', 'serial_baud_max_mbps', 'serial_baud_rate_max_mbps'),
  ('identity_discard', 'brand', NULL),
  ('identity_discard', 'marca', NULL),
  ('identity_discard', 'manufacturer', NULL),
  ('identity_discard', 'fabricante', NULL),
  ('identity_discard', 'vendor', NULL),
  ('identity_discard', 'device_brand', NULL),
  ('identity_discard', 'model', NULL),
  ('identity_discard', 'modelo', NULL),
  ('identity_discard', 'device_model', NULL),
  ('identity_discard', 'model_name', NULL),
  ('identity_discard', 'device_family', NULL),
  ('identity_discard', 'part_number', NULL),
  ('identity_discard', 'numero_de_parte', NULL),
  ('identity_discard', 'número_de_parte', NULL),
  ('identity_discard', 'numero_de_pieza', NULL),
  ('identity_discard', 'número_de_pieza', NULL),
  ('identity_discard', 'n_de_parte', NULL),
  ('identity_discard', 'name', NULL),
  ('identity_discard', 'product_name', NULL),
  ('identity_discard', 'nombre', NULL),
  ('identity_discard', 'sku', NULL),
  ('identity_discard', 'serial_number', NULL),
  ('identity_discard', 'numero_de_serie', NULL),
  ('identity_discard', 'número_de_serie', NULL),
  ('identity_discard', 'firmware_version', NULL),
  ('identity_discard', 'firmware', NULL),
  ('identity_discard', 'firmware_versions', NULL),
  ('identity_discard', 'os_versions', NULL),
  ('identity_discard', 'source_url', NULL),
  ('identity_discard', 'url', NULL),
  ('identity_discard', 'datasheet_url', NULL),
  ('identity_discard', 'datasheet', NULL),
  ('identity_discard', 'image_url', NULL),
  ('identity_discard', 'imagen', NULL)
ON CONFLICT (kind, alias) DO UPDATE SET canonical = EXCLUDED.canonical;
