-- ============================================================
-- SUPABASE + GEMINI 3072 + n8n
-- TABLA: public.solution_pages_table
-- ============================================================

create extension if not exists vector with schema extensions;

drop function if exists public.match_solution_pages(extensions.vector, double precision, integer, jsonb);
drop table if exists public.solution_pages_table cascade;

create table public.solution_pages_table (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(3072) not null,
  created_at timestamptz not null default now()
);

create index if not exists solution_pages_table_metadata_gin_idx
  on public.solution_pages_table
  using gin (metadata jsonb_path_ops);

create index if not exists solution_pages_table_embedding_hnsw_halfvec_cos_idx
  on public.solution_pages_table
  using hnsw ((embedding::extensions.halfvec(3072)) extensions.halfvec_cosine_ops);

create or replace function public.match_solution_pages(
  query_embedding extensions.vector(3072),
  match_threshold double precision default null,
  match_count integer default null,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language plpgsql
stable
set search_path = public, extensions
as $$
declare
  v_filter jsonb := coalesce(filter, '{}'::jsonb);

  v_search_mode text := lower(coalesce(nullif(trim(v_filter->>'search_mode'), ''), 'general'));
  v_page_keys text[];

  v_match_count integer;
  -- v_match_threshold double precision;   -- threshold desactivado (ver más abajo)
begin
  if query_embedding is null then
    raise exception 'query_embedding cannot be null';
  end if;

  if jsonb_typeof(v_filter) is distinct from 'object' then
    raise exception 'filter must be a json object';
  end if;

  -- Validate search_mode
  if v_search_mode not in ('specific', 'general') then
    raise exception 'search_mode must be specific or general';
  end if;

  -- Parse page_keys (siempre viene como array)
  if v_filter ? 'page_keys' then
    if jsonb_typeof(v_filter->'page_keys') = 'array' then
      select array_agg(lower(trim(elem.value::text, '"')))
        into v_page_keys
        from jsonb_array_elements(v_filter->'page_keys') as elem
       where trim(elem.value::text, '"') <> '';
    else
      raise exception 'page_keys must be a JSON array';
    end if;
  else
    v_page_keys := null;
  end if;

  -- Routing validation
  if v_search_mode = 'general' then
    if v_page_keys is not null
       and v_page_keys <> '{general}'
       and array_length(v_page_keys, 1) > 0 then
      raise exception 'search_mode=general does not accept specific page_keys';
    end if;
    v_page_keys := null;
  else
    if v_page_keys is null or array_length(v_page_keys, 1) = 0 then
      raise exception 'search_mode=specific requires at least one page_keys value';
    end if;
    declare
      k text;
    begin
      foreach k in array v_page_keys loop
        if k not in ('conectividad', 'iot', 'sdwan', 'sim-card') then
          raise exception 'invalid page_key: %. Must be one of conectividad, iot, sdwan, sim-card', k;
        end if;
      end loop;
    end;
  end if;

  -- Resolve match_count (solo desde el parámetro de la función)
  v_match_count := greatest(
    coalesce(
      match_count,
      case when v_search_mode = 'specific' then 5 else 7 end
    ), 1
  );

  -- Threshold comentado: puede ser la causa de resultados vacíos
  -- v_match_threshold := coalesce(match_threshold, 0.35);

  return query
  select
    spt.id,
    spt.content,
    spt.metadata,
    (1 - (spt.embedding <=> query_embedding)) as similarity
  from public.solution_pages_table as spt
  where (
      v_page_keys is null
      or coalesce(spt.metadata->>'page_key', '') = any(v_page_keys)
    )
    -- and (1 - (spt.embedding <=> query_embedding)) >= v_match_threshold
  order by spt.embedding <=> query_embedding asc
  limit v_match_count;
end;
$$;

alter table public.solution_pages_table enable row level security;

drop policy if exists "solution_pages_table_select_authenticated" on public.solution_pages_table;
create policy "solution_pages_table_select_authenticated"
  on public.solution_pages_table
  for select
  to authenticated
  using (true);

grant select on public.solution_pages_table to authenticated, service_role;
grant insert, update, delete on public.solution_pages_table to service_role;
grant usage, select on sequence public.solution_pages_table_id_seq to service_role;

revoke all on function public.match_solution_pages(extensions.vector, double precision, integer, jsonb) from public;


grant execute on function public.match_solution_pages(extensions.vector, double precision, integer, jsonb)
  to authenticated, service_role;

notify pgrst, 'reload schema';

